import React, {useState} from 'react';
import {Alert, ScrollView, StyleSheet, Text, View} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import {apiFetch} from '../api/client';
import {Button, Card, Field, sharedStyles} from '../components/ui';
import {colors, spacing} from '../theme';
import {useLoad} from '../hooks/useLoad';

const types = [{key: 'progress', label: 'Work progress'}, {key: 'material_request', label: 'Material request'}, {key: 'material_usage', label: 'Material usage'}, {key: 'workers', label: 'Worker count'}, {key: 'photo', label: 'Site photo'}] as const;
export function SiteUpdateScreen({route, navigation}: any) {
  const {projectId, works} = route.params; const [type, setType] = useState<string>('progress'); const [primary, setPrimary] = useState(''); const [secondary, setSecondary] = useState(''); const [referenceId, setReferenceId] = useState(''); const [saving, setSaving] = useState(false);
  const materials = useLoad(() => apiFetch<{results: {id: number; name: string; unit: string}[]}>('/materials/'), []);
  const submit = async () => {setSaving(true); try {const body: Record<string, string> = {type}; if (type === 'progress') Object.assign(body, {work_id: referenceId, status: secondary, progress: primary}); if (type === 'workers') Object.assign(body, {work_type: primary, worker_count: secondary}); if (type.includes('material')) Object.assign(body, {material_id: referenceId, quantity: primary}); await apiFetch(`/projects/${projectId}/site-updates/`, {method: 'POST', body: JSON.stringify(body)}); Alert.alert('Saved', 'The site update is available to the project team.'); navigation.goBack();} catch (reason) {Alert.alert('Unable to save', reason instanceof Error ? reason.message : 'Please check the form.');} finally {setSaving(false);}};
  const uploadPhoto = async () => {const result = await ImagePicker.launchCameraAsync({mediaTypes: ['images'], quality: 0.8}); if (result.canceled) return; const asset = result.assets[0]; if (!asset) return; const form = new FormData(); form.append('type', 'photo'); form.append('photo', {uri: asset.uri, name: asset.fileName ?? 'site-photo.jpg', type: asset.mimeType ?? 'image/jpeg'} as unknown as Blob); setSaving(true); try {await apiFetch(`/projects/${projectId}/site-updates/`, {method: 'POST', body: form}); Alert.alert('Uploaded', 'The site photo is available to the project team.'); navigation.goBack();} catch (reason) {Alert.alert('Unable to upload', reason instanceof Error ? reason.message : 'Please try again.');} finally {setSaving(false);}};
  return <ScrollView style={sharedStyles.screen} contentContainerStyle={sharedStyles.content}><Text style={sharedStyles.title}>Add site update</Text><View style={styles.choices}>{types.map(item => <Text key={item.key} onPress={() => {setType(item.key); setPrimary(''); setSecondary(''); setReferenceId('');}} style={[styles.choice, type === item.key && styles.selected]}>{item.label}</Text>)}</View><Card>
    {type === 'progress' && <><Text style={styles.label}>Select work</Text>{works.map((item: any) => <Text key={item.id} onPress={() => setReferenceId(String(item.id))} style={[styles.option, referenceId === String(item.id) && styles.optionSelected]}>{item.name}</Text>)}<Field label="Progress note or percentage" value={primary} onChangeText={setPrimary} /><Field label="Status" value={secondary} onChangeText={setSecondary} placeholder="In progress / completed" /></>}
    {type === 'workers' && <><Field label="Work type" value={primary} onChangeText={setPrimary} /><Field label="Worker count" value={secondary} onChangeText={setSecondary} keyboardType="number-pad" /></>}
    {type.includes('material') && <><Text style={styles.label}>Select material</Text>{materials.data?.results.map(item => <Text key={item.id} onPress={() => setReferenceId(String(item.id))} style={[styles.option, referenceId === String(item.id) && styles.optionSelected]}>{item.name} · {item.unit}</Text>)}<Field label="Quantity" value={primary} onChangeText={setPrimary} /></>}
    {type === 'photo' ? <Button title="Take and upload photo" onPress={() => void uploadPhoto()} loading={saving} /> : <Button title="Save site update" onPress={submit} loading={saving} disabled={!primary || (type !== 'workers' && !referenceId)} />}
  </Card></ScrollView>;
}
const styles = StyleSheet.create({choices: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm}, choice: {paddingHorizontal: 12, paddingVertical: 10, borderRadius: 10, backgroundColor: '#fff', color: colors.primaryDark, borderWidth: 1, borderColor: colors.border}, selected: {backgroundColor: colors.primary, color: '#fff', borderColor: colors.primary}, label: {fontWeight: '700', color: colors.text}, option: {padding: 12, borderRadius: 8, backgroundColor: colors.background}, optionSelected: {backgroundColor: colors.primarySoft, color: colors.primary, fontWeight: '700'}});
