# Generated by Django 3.2.17 on 2023-05-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=40)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('date', models.CharField(max_length=100)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
    ]
