# Generated by Django 3.2.17 on 2023-05-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_material_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
