# Generated by Django 3.2.17 on 2023-05-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
