# Generated by Django 3.2.17 on 2023-05-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(max_length=100)),
                ('to_date', models.DateField(max_length=100)),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('WORK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.work')),
            ],
        ),
    ]
