# Generated by Django 3.2.17 on 2023-06-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_account_sub_accounthead_budget_estimate_documents_drawing_estimate_inspection_login_material_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_delivery',
            name='MATERIAL_ISSUED',
        ),
        migrations.RemoveField(
            model_name='material_delivery',
            name='PURCHASER',
        ),
        migrations.RemoveField(
            model_name='material_issued',
            name='MATERIAL',
        ),
        migrations.RemoveField(
            model_name='material_issued',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='material_issued',
            name='STAFF',
        ),
        migrations.RemoveField(
            model_name='material_request',
            name='MATERIAL',
        ),
        migrations.RemoveField(
            model_name='material_request',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='material_request',
            name='STAFF',
        ),
        migrations.RemoveField(
            model_name='material_required',
            name='MATERIAL',
        ),
        migrations.RemoveField(
            model_name='material_required',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='material_usage',
            name='MATERIAL',
        ),
        migrations.RemoveField(
            model_name='material_usage',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='material_usage',
            name='STAFF',
        ),
        migrations.DeleteModel(
            name='material',
        ),
        migrations.DeleteModel(
            name='material_delivery',
        ),
        migrations.DeleteModel(
            name='material_issued',
        ),
        migrations.DeleteModel(
            name='material_request',
        ),
        migrations.DeleteModel(
            name='material_required',
        ),
        migrations.DeleteModel(
            name='material_usage',
        ),
    ]
