# Generated by Django 3.2.17 on 2023-06-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20230615_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('unit', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='material_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=40)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='material_required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='material_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('status', models.CharField(default='pending', max_length=70)),
                ('date', models.CharField(max_length=100)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='material_issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('quantity_issued', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='material_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=50)),
                ('MATERIAL_ISSUED', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material_issued')),
                ('PURCHASER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
        ),
    ]
