# Generated by Django 3.2.17 on 2023-06-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_material_material_delivery_material_issued_material_request_material_required_material_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcotractor_project_allocation',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='subcotractor_project_allocation',
            name='SUBCONTRACTOR',
        ),
        migrations.RemoveField(
            model_name='subcotractor_project_allocation',
            name='WORK',
        ),
        migrations.DeleteModel(
            name='subcontractor_schedule',
        ),
        migrations.DeleteModel(
            name='subcotractor_project_allocation',
        ),
    ]
