# Generated by Django 3.2.17 on 2023-06-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20230615_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcotractor_project_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=40)),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
                ('SUBCONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.subcontractor')),
                ('WORK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.work')),
            ],
        ),
        migrations.CreateModel(
            name='subcontractor_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('SUBCONTRACTOR_PROJECT_ALLOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.subcotractor_project_allocation')),
            ],
        ),
    ]
