# Generated by Django 3.2.17 on 2023-06-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_subcontractor_schedule_subcotractor_project_allocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='material_required',
        ),
    ]
