# Generated by Django 3.2.17 on 2023-06-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_delete_material_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.material')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.project')),
            ],
        ),
    ]
