# Generated by Django 5.2.16 on 2026-07-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_workflow_and_unique_staff_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material_required',
            index=models.Index(fields=['PROJECT', 'category'], name='material_req_project_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'date'], name='project_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_name'], name='project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['estimate_status'], name='project_est_status_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['PROJECT', 'from_date', 'to_date'], name='schedule_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['designation'], name='staff_designation_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['name'], name='staff_name_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['PROJECT', 'workname'], name='work_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='work_progress',
            index=models.Index(fields=['PROJECT', 'date'], name='progress_project_date_idx'),
        ),
    ]
