# Generated by Django 5.2.16 on 2026-08-05 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_quotation_references(apps, schema_editor):
    Quotation = apps.get_model('MyApp', 'quotation')
    enquiry_ids = Quotation.objects.order_by().values_list('ENQUIRY_id', flat=True).distinct()
    for enquiry_id in enquiry_ids:
        quotes = list(Quotation.objects.filter(ENQUIRY_id=enquiry_id).order_by('version', 'id'))
        if not quotes:
            continue
        sequence = quotes[0].pk
        base_number = f'QTN/{sequence:04d}/ETC/{quotes[0].issue_date:%m/%y}'
        for revision, quote in enumerate(quotes):
            quote.sequence_number = sequence
            quote.revision = revision
            quote.quotation_number = base_number if revision == 0 else f'{base_number}-R{revision}'
            if not quote.subject:
                quote.subject = f'Quotation for enquiry {enquiry_id}'
            quote.save(update_fields=(
                'sequence_number', 'revision', 'quotation_number', 'subject',
            ))


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_quotation_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='quotation_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='closing_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='quotation',
            name='material_approval',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mobilization',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_duration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signatory_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signatory_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signatory_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='variations',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(populate_quotation_references, migrations.RunPython.noop),
        migrations.CreateModel(
            name='workflow_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='quotation_deadline', max_length=40)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Urgent')], default='info', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ENQUIRY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notifications', to='MyApp.enquiry')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to='MyApp.login')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='workflow_notice_recipient_idx'), models.Index(fields=['event', 'due_at'], name='workflow_notice_due_idx')],
            },
        ),
    ]
