# Generated by Django 5.2.16 on 2026-08-05 02:56

from django.db import migrations, models


def initialize_counter(apps, schema_editor):
    Quotation = apps.get_model('MyApp', 'quotation')
    Counter = apps.get_model('MyApp', 'quotation_counter')
    largest = Quotation.objects.order_by('-sequence_number').values_list(
        'sequence_number', flat=True,
    ).first() or 0
    Counter.objects.update_or_create(pk=1, defaults={'next_value': largest + 1})


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_enquiry_quotation_deadline_quotation_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RunPython(initialize_counter, migrations.RunPython.noop),
    ]
