"""
Django settings for WMS project.

Generated by 'django-admin startproject' using Django 3.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEVELOPMENT_SECRET_KEY = 'django-insecure-chzb8^qjc#cub*(euoye%!^*xr+-x@kox-)tlsya&-gwet14%j'
SECRET_KEY = os.environ.get('WMS_SECRET_KEY', DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('WMS_DEBUG', 'true').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('WMS_ALLOWED_HOSTS', '*' if DEBUG else '').split(',')
    if host.strip()
]

if not DEBUG and SECRET_KEY == DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured('Set WMS_SECRET_KEY before running with WMS_DEBUG=false.')
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('Set WMS_ALLOWED_HOSTS before running with WMS_DEBUG=false.')

# "16.16.159.84"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'MyApp.apps.MyappConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('MyApp.api.authentication.SignedTokenAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('MyApp.api.permissions.ApiAuthenticated',),
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',),
    'EXCEPTION_HANDLER': 'MyApp.api.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_RATES': {'login': '10/minute'},
}

MESSAGE_TAGS = {40: 'danger'}

WMS_MOBILE_TOKEN_MAX_AGE = int(os.environ.get('WMS_MOBILE_TOKEN_MAX_AGE', str(30 * 24 * 60 * 60)))

# Outbound quotation email. Production credentials must be supplied through
# environment variables or the deployment secret manager, never committed.
EMAIL_BACKEND = os.environ.get(
    'WMS_EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('WMS_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('WMS_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('WMS_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('WMS_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('WMS_EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('WMS_EMAIL_USE_SSL', 'false').lower() in ('1', 'true', 'yes')
EMAIL_TIMEOUT = int(os.environ.get('WMS_EMAIL_TIMEOUT', '20'))
DEFAULT_FROM_EMAIL = os.environ.get(
    'WMS_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'quotations@exalterpro.com',
)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('Enable only one of WMS_EMAIL_USE_TLS or WMS_EMAIL_USE_SSL.')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'MyApp.middleware.LegacySessionAuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'MyApp.middleware.LegacyScriptAlertMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASE_ENGINE = os.environ.get('WMS_DB_ENGINE', 'sqlite').strip().lower()
if DATABASE_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.environ.get('WMS_DB_NAME', BASE_DIR / 'db.sqlite3')),
        }
    }
elif DATABASE_ENGINE == 'postgresql':
    required_database_settings = ('WMS_DB_NAME', 'WMS_DB_USER', 'WMS_DB_PASSWORD', 'WMS_DB_HOST')
    missing_database_settings = [name for name in required_database_settings if not os.environ.get(name)]
    if missing_database_settings:
        raise ImproperlyConfigured(
            f'Missing PostgreSQL settings: {", ".join(missing_database_settings)}'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['WMS_DB_NAME'],
            'USER': os.environ['WMS_DB_USER'],
            'PASSWORD': os.environ['WMS_DB_PASSWORD'],
            'HOST': os.environ['WMS_DB_HOST'],
            'PORT': os.environ.get('WMS_DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('WMS_DB_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {'sslmode': os.environ.get('WMS_DB_SSLMODE', 'require')},
        }
    }
else:
    raise ImproperlyConfigured('WMS_DB_ENGINE must be sqlite or postgresql.')


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Qatar'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT =os.path.join(BASE_DIR,'media')
MEDIA_URL ='/media/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Backups are deliberately stored outside the code and upload directories.
# The command is scheduled by the operating system or cloud scheduler so web
# worker scaling can never create duplicate backup jobs.
WMS_BACKUP_ROOT = os.environ.get('WMS_BACKUP_ROOT', str(BASE_DIR.parent / 'wms_backups'))
WMS_BACKUP_RETENTION_DAYS = int(os.environ.get('WMS_BACKUP_RETENTION_DAYS', '30'))

DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# Secure defaults for production; each option remains explicitly configurable.
SESSION_COOKIE_SECURE = os.environ.get('WMS_SESSION_COOKIE_SECURE', str(not DEBUG)).lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('WMS_CSRF_COOKIE_SECURE', str(not DEBUG)).lower() in ('1', 'true', 'yes')
SECURE_SSL_REDIRECT = os.environ.get('WMS_SECURE_SSL_REDIRECT', 'false').lower() in ('1', 'true', 'yes')
SECURE_HSTS_SECONDS = int(os.environ.get('WMS_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
if os.environ.get('WMS_BEHIND_HTTPS_PROXY', 'false').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('WMS_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
